### ISSUE TITLE
1장 예제파일에 test.csv가 없습니다.

### ISSUE THREAD

**Issue by kyungkoo** [Ungsik-Yun/pythonfordev#1]
1장 예제를 따라하는 과정에서 ch01 디렉터리의 test.csv를 참조하는 부분이 있는데 예제 파일을 다운로드 받았음에도 불구하고 해당 파일이 없네요.

**Comment by Ungsik-Yun** [comment]
ch1 폴더에 해당 csv 파일을 추가하였습니다. 감사합니다!
